### ISSUE TITLE
No parallelization during nearest neighbors computation

### ISSUE THREAD

**Issue by dylkot** [scverse/scanpy#913]
I'm using scanpy with the following version
- scanpy 1.4.4.post1 
- numba 0.45.1
- numpy 1.17.2

on a Ubuntu virtual machine with 16 cpus. In the example data below, I have 47933 cells × 41 genes. When I run

```
sc.pp.neighbors(adata, n_neighbors=100, n_pcs=12)
```
it empirically uses only 1 core and takes 1 min 35s and I get the warning:
```
/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/rp_tree.py", line 135:
@numba.njit(fastmath=True, nogil=True, parallel=True)
def euclidean_random_projection_split(data, indices, rng_state):
^

  self.func_ir.loc))
/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/nndescent.py:92: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/utils.py", line 409:
@numba.njit(parallel=True)
def build_candidates(current_graph, n_vertices, n_neighbors, max_candidates, rng_state):
^

  current_graph, n_vertices, n_neighbors, max_candidates, rng_state
/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  self.func_ir.loc))
```

when I run
```
from joblib import parallel_backend
with parallel_backend('threading', n_jobs=15):
    sc.pp.neighbors(adata, n_neighbors=100, n_pcs=12)
```

as suggested in #659, it takes 1 min 28 seconds, empirically mostly uses 1 cpu, and gives the following warning

```
/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/rp_tree.py", line 135:
@numba.njit(fastmath=True, nogil=True, parallel=True)
def euclidean_random_projection_split(data, indices, rng_state):
^

  self.func_ir.loc))
/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  self.func_ir.loc))
```

Are there any tips on how I can benefit from parallelization in these nearest neighbor computations? This is the bottleneck in my work flow.

**Comment by flying-sheep** [comment]
What did you set [`sc.settings.n_jobs`](https://icb-scanpy.readthedocs-hosted.com/en/stable/api/scanpy._settings.ScanpyConfig.n_jobs.html) to?

**Comment by dylkot** [comment]
I actually had not set that attribute. But I just tested it now

```
sc.settings.n_jobs = 15
sc.pp.neighbors(adata_B, n_neighbors=100, n_pcs=11)
```

OR

```
sc.settings.n_jobs = 15
with parallel_backend('threading', n_jobs=15):
    sc.pp.neighbors(adata_B, n_neighbors=100, n_pcs=11)
```

and in either case it only uses one cpu and takes the same amount of time as above.

**Comment by gokceneraslan** [comment]
Aren't umap 0.4 and latest pynndescent required for the parallelization support? 🤔

**Comment by dylkot** [comment]
the latest umap version on pypi is umap-learn 0.3.10 which is the version I have and also the version on Github as far as I can tell. Do I need to install in another way or from a development branch or something?

I did not have pynndescent installed but just added it: pynndescent-0.3.3

However, it still is not using parallelization in the KNN calculation with either of the commands above

**Comment by dylkot** [comment]
OK I install umap 0.4 

```
pip install git+git://github.com/lmcinnes/umap@0.4dev
```

However, it doesn't seem to run any faster and actually throws an error now

```
sc.pp.neighbors(adata_B, n_neighbors=100, n_pcs=11)
```
gives
```
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, copy)
     93         n_neighbors=n_neighbors, knn=knn, n_pcs=n_pcs, use_rep=use_rep,
     94         method=method, metric=metric, metric_kwds=metric_kwds,
---> 95         random_state=random_state,
     96     )
     97     adata.uns['neighbors'] = {}

/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    681                 knn_distances,
    682                 self._adata.shape[0],
--> 683                 self.n_neighbors,
    684             )
    685         # overwrite the umap connectivities if method is 'gauss'

/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    322     distances = get_sparse_matrix_from_indices_distances_umap(knn_indices, knn_dists, n_obs, n_neighbors)
    323 
--> 324     return distances, connectivities.tocsr()
    325 
    326 

AttributeError: 'tuple' object has no attribute 'tocsr'
```

**Comment by gokceneraslan** [comment]
This should be fixed in scanpy master branch.

**Comment by dylkot** [comment]
So now I have scanpy installed from master branch:

scanpy 1.4.5.dev175+g64f04d8
umap-learn 0.4.0
pynndescent 0.3.3

but still no luck with any of the commands above with or without first specifying sc.settings.n_jobs = 15

```
sc.settings.n_jobs = 15
with parallel_backend('threading', n_jobs=15):
    sc.pp.neighbors(adata, n_neighbors=100, n_pcs=12)
```

gives the warning

```
/opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/numba/compiler.py:602: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "../../../../../opt/miniconda3/envs/py37_2/lib/python3.7/site-packages/umap/nndescent.py", line 47:
    @numba.njit(parallel=True)
    def nn_descent(
    ^

  self.func_ir.loc))
```

and now takes 1min 29s

**Comment by flying-sheep** [comment]
Ah I see. Sorry about the red herring with `sc.settings.n_jobs`, all those warnings seem to come directly from umap code.

So according to @tomwhite, only umap 0.4 and pynndescent need to be installed and it should automatically be parallelized. Scanpy doesn’t effect this in any way.

You should probably report this to the umap repo. Please write here once you openend an issue there.

The only thing we can to is to call umap in a way that respects our settings once this is fixed.

**Comment by dylkot** [comment]
Hi @flying-sheep, thanks for the reply. I opened lmcinnes/umap#317.

**Comment by dylkot** [comment]
Leland replied that the parallelization isn't fully implement even in umap 0.4 but that a temporary work around is as below (which is what I'm doing in my local installation):

If you just want to make use of 16 cores then the other option is in umap/umap_.py where it calls pynndescent add an extra option n_jobs=-1, which will turn on the (slightly memory intensive) threaded implementation of nndescent that exists in pynndescent v0.3.

**Comment by flying-sheep** [comment]
OK thank you! Well there’s nothing for us to do here as this would need editing umap’s code. We will continue to import umap and won’t ship a modified version so you need to modify your own copy of umap or wait for @lmcinnes to implement an API for it.

**Comment by tomwhite** [comment]
I've written up a demo of how to run parallel NN and UMAP here: https://github.com/theislab/scanpy_usage/pull/17.

The trick for NN is to a) install pyndescent and b) call the NN algortihm from within a joblib parallel context manager:

```python
from joblib import parallel_backend
with parallel_backend('threading', n_jobs=16):
        sc.pp.neighbors(adata)
```

**Comment by flying-sheep** [comment]
@dylkot demonstrated that this doesn’t have much effect though, right?

**Comment by dylkot** [comment]
Yes @flying-sheep is right. Even with UMAP 0.4 and pynndescent 0.3.3 installed, the parallel_backend code did not change the number of CPUs used for the core nn_descent step, so the runtime was approximately the same as just running sc.pp.neighbors(adata) without the joblib parallel context manager

**Comment by tomwhite** [comment]
Ah yes - sorry I missed the context manager bit from earlier in this thread. I tried running this earlier today using the script in theislab/scanpy_usage#17, and for 130K cells NN took 53s unoptimized vs 35s optimized (32 cores). (Not a proportionate speedup, but still worthwhile.) The UMAP speedup shown in that script is significant too.

I see that there is a UMAP issue to discuss this further.

**Comment by dylkot** [comment]
Ahh interesting. I am trying your setup for a dataset of 212457 cells on a 32 core, 208 GB RAM VM and unfortunately having memory issues if I set n_jobs to be anything greater than 1. If I request 2 jobs, it allocates a (2 x 8498320000 x 4) np.float32 array and if I request 29 jobs it allocates a (29 x 586160000 x 4) array, either of which is too much. So I guess I'm stuck for now. Thank you for all the help though.

**Comment by dylkot** [comment]
@tomwhite, thanks for posting this script. The setup steps ultimately seem to work for me and to produce code that uses all of the allotted cores but it also increases the memory overhead dramatically such that I need >250 GB of RAM which doesn't seem worth it in this case.
